# Generated by Django 5.1.6 on 2025-03-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_memberworship_member_worships_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blessing_date', models.DateField()),
                ('name_of_blessing', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlessingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blessings.blessing')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
