# Generated by Django 5.1.6 on 2025-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blessings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blessing",
            name="name_of_blessing",
            field=models.CharField(max_length=255),
        ),
    ]
