# Generated by Django 5.1.6 on 2025-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessings', '0002_blessing_id_alter_blessing_name_of_blessing'),
        ('members', '0003_memberworship_member_worships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessing',
            name='members',
            field=models.ManyToManyField(related_name='blessings', to='members.member'),
        ),
        migrations.DeleteModel(
            name='BlessingList',
        ),
    ]
