# Generated by Django 5.1.6 on 2025-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessings', '0003_blessing_members_delete_blessinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessing',
            name='chaenbo',
            field=models.IntegerField(choices=[(1, 'Vertical'), (2, 'Horizontal')], default=1),
        ),
    ]
