# Generated by Django 5.1.6 on 2025-03-16 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessings', '0004_blessing_chaenbo'),
        ('worship', '0004_remove_guest_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBlessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blessings.blessing')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.guest')),
            ],
        ),
    ]
