# GET http://localhost:8000/api/members
# Content-Type: application/json
# Authorization: Bearer eyJbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NzEzMzUwLCJpYXQiOjE3Mzk3MDk3NTAsImp0aSI6IjExYmViZWIzMTNkMzQxZGE5YTgxNjU4NzQzMWU3ODM0IiwidXNlcl9pZCI6MX0.BTVhUQiiy8rb869vSjS4MJtgBHZfyBmOq3WlIsBJq9E

# {
    
# }



# POST http://localhost:8000/api/login
# Content-Type: application/json

# {
#     "username": "admin",
#     "password": "admin"
# }

POST http://localhost:8000/api/refresh-token 
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczOTc5NjIzOCwiaWF0IjoxNzM5NzA5ODM4LCJqdGkiOiI4OGE5YzkzNGNhMTE0ZmUyOTdjODMwNmYzYzkxYTU2NiIsInVzZXJfaWQiOjF9.Re61fTv7loq0ZmGV8j70QWMgJMW0GjUdkent0qWkXIo"
}