# Generated by Django 5.1.6 on 2025-04-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('chaenbo', models.TextField(choices=[('Vertical', 'Vertical'), ('Horizontal', 'Horizontal')])),
            ],
        ),
        migrations.CreateModel(
            name='BlessingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Member', 'Member'), ('Guest', 'Guest')])),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blessing.blessing')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blessing_invited_by', to='member.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blessing_member', to='member.member')),
            ],
        ),
    ]
