# Generated by Django 5.1.6 on 2025-05-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='member.member'),
        ),
    ]
