# Generated by Django 5.1.6 on 2025-02-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('subregion', models.CharField(blank=True, max_length=64, null=True)),
                ('nation', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.currency'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.church')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('title', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.')])),
                ('given_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('family_name', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField()),
                ('generation', models.CharField(max_length=64)),
                ('blessing_status', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('blessed_year', models.DateField()),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Separated'), (4, 'Divorced')])),
                ('spiritual_birthday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('membership_category', models.IntegerField(choices=[(1, 'Regular'), (2, 'Associate'), (3, 'Registered'), (4, 'Inactive')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.family')),
                ('spiritual_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_spiritual_parent', to='members.member')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_spouse', to='members.member')),
            ],
        ),
    ]
