# Generated by Django 5.1.6 on 2025-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
