# Generated by Django 5.1.6 on 2025-02-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_country_region'),
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('worship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.worship')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='worships',
            field=models.ManyToManyField(through='members.MemberWorship', to='worship.worship'),
        ),
        migrations.AddConstraint(
            model_name='memberworship',
            constraint=models.UniqueConstraint(fields=('member', 'worship'), name='unique_member_worship'),
        ),
    ]
