# Generated by Django 5.1.6 on 2025-04-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='subregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.subregion'),
        ),
    ]
