# Generated by Django 5.1.6 on 2025-02-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_country_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worship',
            fields=[
                ('worship_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('worship_type', models.IntegerField(choices=[(1, 'Onsite'), (2, 'Online')])),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.church')),
            ],
        ),
    ]
