# Generated by Django 5.1.6 on 2025-03-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberworship_member_worships_and_more'),
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nation', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='GuestWorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.guest')),
                ('worship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.worship')),
            ],
        ),
    ]
