# Generated by Django 5.1.6 on 2025-03-16 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberworship_member_worships_and_more'),
        ('worship', '0002_guest_guestworship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
