# Generated by Django 5.1.6 on 2025-03-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0003_alter_guest_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='nation',
        ),
    ]
