# Generated by Django 5.1.6 on 2025-04-22 09:43

import django.db.models.deletion
import worship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('worship_type', models.TextField(choices=[('Onsite', 'Onsite'), ('Online', 'Online')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worship.models.upload_worship_photo)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
        ),
        migrations.CreateModel(
            name='WorshipAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Member', 'Member'), ('Guest', 'Guest')])),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_invited_by', to='member.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_member', to='member.member')),
                ('worship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.worshipevent')),
            ],
        ),
    ]
