# Generated by Django 5.1.6 on 2025-04-23 01:13

import django.db.models.deletion
import worship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worshipevent',
            name='photo',
        ),
        migrations.CreateModel(
            name='WorshipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worship.models.upload_worship_photo)),
                ('worship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worship.worshipevent')),
            ],
        ),
    ]
