# Generated by Django 5.1.6 on 2025-02-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('subregion', models.CharField(max_length=64)),
                ('nation', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('member_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255)),
                ('title', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.')])),
                ('given_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('family_name', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Separated'), (4, 'Divorced')])),
                ('spiritual_birthday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('membership_category', models.IntegerField(choices=[(1, 'Regular'), (2, 'Associate'), (3, 'Registered'), (4, 'Inactive')])),
                ('spiritual_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_spiritual_parent', to=settings.AUTH_USER_MODEL)),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_spouse', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.family')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
